# Generated by Django 4.1.7 on 2023-04-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='calories',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='food',
            name='interesting_fact',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='food',
            name='deathdoze',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='food',
            name='searched',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Fact',
        ),
    ]
