# Generated by Django 4.1.7 on 2023-04-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_food_calories_food_image_food_interesting_fact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(default='https://goo.su/swyUm5', upload_to='media/'),
        ),
    ]
