# Generated by Django 4.1.7 on 2023-04-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_comprasion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='deathdoze',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='food',
            name='searched',
            field=models.IntegerField(default=0),
        ),
    ]
