# Generated by Django 4.1.4 on 2023-05-06 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
