# Generated by Django 4.1.7 on 2023-05-21 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_lunch_dinner_breakfast'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fact',
        ),
    ]
