# Generated by Django 4.1.4 on 2023-04-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_rename_complaints_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='post_id',
            field=models.IntegerField(default=0),
        ),
    ]
