# Generated by Django 4.1.7 on 2023-04-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(default='https://goo.su/swyUm5', upload_to='media/images/'),
        ),
    ]
