# Generated by Django 4.1.7 on 2023-04-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_vitaminfood_food_alter_vitaminfood_vitamin'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='vitamins',
            field=models.ManyToManyField(to='App.vitamin'),
        ),
        migrations.DeleteModel(
            name='VitaminFood',
        ),
    ]
