# Generated by Django 4.1.4 on 2023-04-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_complaint_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
