# Generated by Django 4.1.7 on 2023-05-09 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_complaint'),
        ('App', '0005_food_vitamins_delete_vitaminfood'),
    ]

    operations = [
    ]
