# Generated by Django 4.1.4 on 2023-04-05 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_complaint_is_checked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
