# Generated by Django 4.1.7 on 2023-04-22 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='fruit_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.food'),
        ),
    ]
