# Generated by Django 4.1.7 on 2023-05-14 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0014_alter_food_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=1000)),
                ('author', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comprasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='vitamins',
            field=models.ManyToManyField(to='App.vitamin'),
        ),
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(default='https://goo.su/swyUm5', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='food',
            name='interesting_fact',
            field=models.CharField(default='ЕСЛИ ВИДИШЬ ЭТУ НАДПИСЬ, ТО ДОБАВЬ ИНТЕРЕСНЫЙ ФАКТ', max_length=1000),
        ),
        migrations.DeleteModel(
            name='VitaminFood',
        ),
        migrations.AddField(
            model_name='fact',
            name='food',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.food'),
        ),
        migrations.AddField(
            model_name='comprasion',
            name='fruit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.food'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='fruit_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.food'),
        ),
    ]
